language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository/

#services:
#  - mysql
#
#before_install:
#  - mysql -e 'CREATE DATABASE myapp_test;'

before_script:
  - export PATH=$PATH:$HOME/bin/

install:
  - mvn install -DskipTests=true -U -Dmaven.javadoc.skip=true -B -V

script:
  - mvn -e verify deploy
  - ./deploy/cf.sh
  - ./deploy/deploy.sh